# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(370, 720))
        MainWindow.setMaximumSize(QtCore.QSize(370, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"resources\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #2c2a2b;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(65, 72, 240, 350))
        self.image.setStyleSheet("border: 2 solid #535152;")
        self.image.setText("")
        self.image.setTextFormat(QtCore.Qt.AutoText)
        self.image.setPixmap(QtGui.QPixmap("../temp.jpeg"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 425, 61))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.caption = QtWidgets.QLabel(self.frame)
        self.caption.setGeometry(QtCore.QRect(117, 4, 135, 35))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(26)
        self.caption.setFont(font)
        self.caption.setStyleSheet("color: rgb(255, 82, 51);")
        self.caption.setObjectName("caption")
        self.questionNumber = QtWidgets.QLabel(self.frame)
        self.questionNumber.setGeometry(QtCore.QRect(133, 40, 103, 24))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.questionNumber.setFont(font)
        self.questionNumber.setStyleSheet("color: #f0f0f0;")
        self.questionNumber.setObjectName("questionNumber")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(254, 10, 121, 20))
        self.line_2.setStyleSheet("background:none;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 111, 20))
        self.line_3.setStyleSheet("background:none;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setEnabled(True)
        self.question.setGeometry(QtCore.QRect(120, 432, 129, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(22)
        self.question.setFont(font)
        self.question.setStyleSheet("color: #f0f0f0;")
        self.question.setObjectName("question")
        self.jeon_jung_kook = QtWidgets.QPushButton(self.centralwidget)
        self.jeon_jung_kook.setGeometry(QtCore.QRect(20, 467, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.jeon_jung_kook.setFont(font)
        self.jeon_jung_kook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}")
        self.jeon_jung_kook.setObjectName("jeon_jung_kook")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 437, 115, 20))
        self.line_4.setStyleSheet("background:none;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(255, 437, 118, 20))
        self.line_5.setStyleSheet("background:none;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.junk_ho_seok = QtWidgets.QPushButton(self.centralwidget)
        self.junk_ho_seok.setGeometry(QtCore.QRect(20, 547, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.junk_ho_seok.setFont(font)
        self.junk_ho_seok.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}\n"
"")
        self.junk_ho_seok.setObjectName("junk_ho_seok")
        self.kim_nam_joon = QtWidgets.QPushButton(self.centralwidget)
        self.kim_nam_joon.setGeometry(QtCore.QRect(200, 467, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.kim_nam_joon.setFont(font)
        self.kim_nam_joon.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}\n"
"")
        self.kim_nam_joon.setObjectName("kim_nam_joon")
        self.kim_seok_jin = QtWidgets.QPushButton(self.centralwidget)
        self.kim_seok_jin.setGeometry(QtCore.QRect(200, 547, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.kim_seok_jin.setFont(font)
        self.kim_seok_jin.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}\n"
"")
        self.kim_seok_jin.setObjectName("kim_seok_jin")
        self.min_yoon_gi = QtWidgets.QPushButton(self.centralwidget)
        self.min_yoon_gi.setGeometry(QtCore.QRect(20, 507, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.min_yoon_gi.setFont(font)
        self.min_yoon_gi.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}")
        self.min_yoon_gi.setObjectName("min_yoon_gi")
        self.kim_tae_hyung = QtWidgets.QPushButton(self.centralwidget)
        self.kim_tae_hyung.setGeometry(QtCore.QRect(110, 587, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.kim_tae_hyung.setFont(font)
        self.kim_tae_hyung.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}\n"
"")
        self.kim_tae_hyung.setObjectName("kim_tae_hyung")
        self.park_ji_min = QtWidgets.QPushButton(self.centralwidget)
        self.park_ji_min.setGeometry(QtCore.QRect(200, 507, 150, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.park_ji_min.setFont(font)
        self.park_ji_min.setStyleSheet("QPushButton {\n"
"    background-color: rgb(83, 81, 82);\n"
"    color: #d7d6d6;\n"
"}\n"
"")
        self.park_ji_min.setObjectName("park_ji_min")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 620, 441, 20))
        self.line_6.setStyleSheet("background:none;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.compliment = QtWidgets.QLabel(self.centralwidget)
        self.compliment.setEnabled(True)
        self.compliment.setGeometry(QtCore.QRect(10, 640, 350, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compliment.sizePolicy().hasHeightForWidth())
        self.compliment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(23)
        self.compliment.setFont(font)
        self.compliment.setStyleSheet("color: #f0f0f0;")
        self.compliment.setText("")
        self.compliment.setAlignment(QtCore.Qt.AlignCenter)
        self.compliment.setObjectName("compliment")
        self.next_question = QtWidgets.QPushButton(self.centralwidget)
        self.next_question.setGeometry(QtCore.QRect(95, 680, 180, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.next_question.setFont(font)
        self.next_question.setStyleSheet("QPushButton {\n"
"    background-color: rgb(182, 58, 36);\n"
"    color: #f0f0f0;\n"
"}\n"
"")
        self.next_question.setObjectName("next_question")
        self.results = QtWidgets.QPushButton(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(105, 680, 160, 33))
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPixelSize(18)
        self.results.setFont(font)
        self.results.setStyleSheet("QPushButton {\n"
"    background-color: rgb(182, 58, 36);\n"
"    color: #f0f0f0;\n"
"}\n"
"")
        self.results.setObjectName("results")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OnlyBtsFuns"))
        self.caption.setText(_translate("MainWindow", "OnlyBtsFuns"))
        self.questionNumber.setText(_translate("MainWindow", "Вопрос 1 из 10"))
        self.question.setText(_translate("MainWindow", " Кто на фото?"))
        self.jeon_jung_kook.setText(_translate("MainWindow", "Jeon Jung Kook"))
        self.junk_ho_seok.setText(_translate("MainWindow", "Jung Ho Seok"))
        self.kim_nam_joon.setText(_translate("MainWindow", "Kim Nam Joon"))
        self.kim_seok_jin.setText(_translate("MainWindow", "Kim Seok Jin"))
        self.min_yoon_gi.setText(_translate("MainWindow", "Min Yoon Gi"))
        self.kim_tae_hyung.setText(_translate("MainWindow", "Kim Tae Hyung"))
        self.park_ji_min.setText(_translate("MainWindow", "Park Ji Min"))
        self.next_question.setText(_translate("MainWindow", "Следующий вопрос"))
        self.results.setText(_translate("MainWindow", "Результат"))
