# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Warning(object):
    def setupUi(self, Warning):
        Warning.setObjectName("Warning")
        Warning.resize(480, 280)
        Warning.setMinimumSize(QtCore.QSize(480, 280))
        Warning.setMaximumSize(QtCore.QSize(480, 280))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Warning.setWindowIcon(icon)
        Warning.setStyleSheet("background-color: #2c2a2b;")
        self.centralwidget = QtWidgets.QWidget(Warning)
        self.centralwidget.setObjectName("centralwidget")
        self.comment = QtWidgets.QLabel(self.centralwidget)
        self.comment.setEnabled(True)
        self.comment.setGeometry(QtCore.QRect(20, 80, 440, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment.sizePolicy().hasHeightForWidth())
        self.comment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ponter")
        font.setPointSize(12)
        self.comment.setFont(font)
        self.comment.setStyleSheet("color: #f0f0f0;")
        self.comment.setLineWidth(2)
        self.comment.setTextFormat(QtCore.Qt.AutoText)
        self.comment.setAlignment(QtCore.Qt.AlignCenter)
        self.comment.setWordWrap(True)
        self.comment.setObjectName("comment")
        Warning.setCentralWidget(self.centralwidget)

        self.retranslateUi(Warning)
        QtCore.QMetaObject.connectSlotsByName(Warning)

    def retranslateUi(self, Warning):
        _translate = QtCore.QCoreApplication.translate
        Warning.setWindowTitle(_translate("Warning", "OnlyBTSFuns"))
        self.comment.setText(_translate("Warning", "Для корректной работы приложения зайдите в папку \"resources\", откройте файл \"Ponter.ttf\" и установите данный шрифт. После чего перезапустите приложение"))
